
SORT_MODE__LAPS = 0
SORT_MODE__LAPTIME = 1

COMP_MODE__TRAINING = 3
COMP_MODE__QUALIFYING_LAPS = 4
COMP_MODE__QUALIFYING_TIME = 5
COMP_MODE__QUALIFYING_LAPS_SEQ = 6
COMP_MODE__QUALIFYING_TIME_SEQ = 7
COMP_MODE__RACE_LAPS = 8
COMP_MODE__RACE_TIME = 9

DUMMY_IDS = ['d', 'dummy']

BOX_MIN = 2
TTS_LAPS_REMAINING = [1, 2]
TTS_TIME_REMAINING = [15, 8]

TTS_LAPS_MOD = 5
TTS_TIME_MOD = 30
