
SORT_MODE__LAPS = 0
SORT_MODE__LAPTIME = 1

COMP_MODE__TRAINING = 3
COMP_MODE__QUALIFYING_LAPS = 4
COMP_MODE__QUALIFYING_TIME = 5
COMP_MODE__QUALIFYING_LAPS_SEQ = 6
COMP_MODE__QUALIFYING_TIME_SEQ = 7
COMP_MODE__RACE_LAPS = 8
COMP_MODE__RACE_TIME = 9
